spring:
  datasource:
    url: jdbc:h2:mem:hello;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  security:
    user:
      name: dev
      password: dev

logging:
  level:
    com.example.helloworld: DEBUG
    org.springframework.web: INFO
