CREATE TABLE greeting (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale   VARCHAR(8)   NOT NULL,
    template VARCHAR(255) NOT NULL,
    CONSTRAINT uq_greeting_locale UNIQUE (locale)
);

INSERT INTO greeting (locale, template) VALUES
    ('en', 'Hello, %s!'),
    ('es', '¡Hola, %s!'),
    ('fr', 'Bonjour, %s !'),
    ('de', 'Hallo, %s!');
